modLoader="${forge_loader}"
loaderVersion="${forge_loader_version}"
license="MIT"
issueTrackerURL="https://github.com/BluSpring/UnityTranslate/issues"

[[mods]]
    modId="unitytranslate"
    version="${mod_version}"
    displayName="UnityTranslate"
    logoFile="icon.png"
    credits="Thanks to Argos Open Tech for creating LibreTranslate, without it this mod would not have been possible."
    authors="BluSpring"
    description='''
    A mod designed for free live translation, inspired by the QSMP. Mainly created for the Unity Multiplayer server, and for public release towards the multilingual Minecraft community.
    '''

[[dependencies.unitytranslate]]
    modId="${mod_loader_name}"
    ${FUCKING_REQUIRED}
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unitytranslate]]
    modId="minecraft"
    ${FUCKING_REQUIRED}
    versionRange="[${mc_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unitytranslate]]
    modId="kotlinforforge"
    ${FUCKING_REQUIRED}
    versionRange="[${forge_kotlin_version},)"
    ordering="NONE"
    side="BOTH"

[[dependencies.unitytranslate]]
    modId="architectury"
    ${FUCKING_REQUIRED}
    versionRange="[${architectury_version},)"
    ordering="NONE"
    side="BOTH"

[[mixins]]
    config = "unitytranslate.mixins.json"